export const GET_DRAGONS_LIST = 'GET_DRAGONS_LIST';
export const GET_DRAGONS_LIST_SUCCESS = 'GET_DRAGONS_LIST_SUCCESS';
export const GET_DRAGONS_LIST_FAIL = 'GET_DRAGONS_LIST_FAIL';
export const SORT_DRAGON_LIST = 'SORT_DRAGON_LIST';

export const LOGIN_INIT = 'LOGIN_INIT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const SAVE_DRAGON = 'SAVE_DRAGON';
export const SAVE_DRAGON_SUCCESS = 'SAVE_DRAGON_SUCCESS';
export const SAVE_DRAGON_FAIL = 'SAVE_DRAGON_FAIL';

export const DELETE_DRAGON_INIT = 'DELETE_DRAGON_INIT';
export const DELETE_DRAGON_SUCCESS = 'DELETE_DRAGON_SUCCESS';
export const DELETE_DRAGON_FAIL = 'DELETE_DRAGON_FAIL';

export const CREATE_DRAGON = 'CREATE_DRAGON';
export const CREATE_DRAGON_SUCCESS = 'CREATE_DRAGON_SUCCESS';
export const CREATE_DRAGON_FAIL = 'CREATE_DRAGON_FAIL';