server:
  port: 8501

spring:
  jackson:
    deserialization:
      adjust_dates_to_context_time_zone: false
    serialization:
      write_dates_as_timestamps: false
      write_dates_with_zone_id: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true

flyway:
  enabled: true