spring:
  jackson:
    deserialization:
      adjust_dates_to_context_time_zone: false
    serialization:
      write_dates_as_timestamps: false
      write_dates_with_zone_id: true

flyway:
  enabled: false